# Project information
site_name: Certpages
site_description: 'Resource For All Your Certifications'
site_url: 'https://wwww.certpages.com'

# Configuration
theme:
  name: 'material'
  custom_dir: 'src'
  palette:
    primary: 'black'
    accent: 'blue'
  logo:
    icon: 'class'
  favicon: 'assets/images/favicon1.png'

# Copyright
copyright: 'Copyright &copy; 2019 - 2020 Certpages'

# Google Analytics
google_analytics:
  - 'UA-154979472-1'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition  
  - toc:
      permalink: true

# Plugins
plugins:
  - search

# Customization
extra:
  disqus: 'certpages'

# Page tree
nav:
  - 'AWS Cloud Practitioner' : AWS/CloudPractitioner.md
  - 'AWS Solutions Architect – Associate' : AWS/SolutionsArchitect–Associate.md
  - 'AWS Developer - Associate' : AWS/Developer-Associate.md
  - 'AWS SysOps Administrator - Associate' : AWS/SysOpsAdministrator-Associate.md
  - 'AWS Solutions Architect - Professional' : AWS/SolutionsArchitect-Professional.md
  - 'AWS Certified DevOps Engineer - Professional' : AWS/DevOpsEngineer-Professional.md
  