# Project information
site_name: Certpages
site_description: 'Resource For All Your Certifications'

# Configuration
theme:
  name: 'material'
  custom_dir: 'src'
  palette:
    primary: 'black'
    accent: 'blue'
  logo:
    icon: 'pages'
    favicon: 'pages'

# Copyright
copyright: 'Copyright &copy; 2019 - 2020 Certpages'

# Google Analytics
google_analytics:
  - 'UA-XXXXXXXX-X'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition  
  - toc:
      permalink: true

# Plugins
plugins:
  - search

# Page tree
nav:
  - AWS:
    - 'Cloud Practitioner' : AWS/CloudPractitioner.md
    - 'Solutions Architect – Associate' : AWS/SolutionsArchitect–Associate.md
    - 'Developer - Associate' : AWS/Developer-Associate.md
    - 'SysOps Administrator - Associate' : AWS/SysOpsAdministrator-Associate.md
  
  - Cisco:
    - 'Cloud Practitioner' : AWS/CloudPractitioner.md  

  - Comptia:
    - 'Cloud Practitioner' : AWS/CloudPractitioner.md

  - Microsoft:
    - 'Cloud Practitioner' : AWS/CloudPractitioner.md

  - VMWare:
    - 'Cloud Practitioner' : AWS/CloudPractitioner.md

  - ISC2:
    - 'Cloud Practitioner' : AWS/CloudPractitioner.md

  - Redhat:
    - 'Cloud Practitioner' : AWS/CloudPractitioner.md
  
  - GCP:
    - 'Cloud Practitioner' : AWS/CloudPractitioner.md

  - ITIL:
    - 'Cloud Practitioner' : AWS/CloudPractitioner.md

  - PMI:
    - 'Cloud Practitioner' : AWS/CloudPractitioner.md

  - EC-Councile:
    - 'Cloud Practitioner' : AWS/CloudPractitioner.md

  - GIAC:
    - 'Cloud Practitioner' : AWS/CloudPractitioner.md
  
  