# Project information
site_name: Certpages
site_description: 'Resources For All Your IT Certifications'
site_url: 'https://certpages.com'

# Configuration
theme:
  favicon: 'fcertpages.ico'
  name: 'material'
  custom_dir: 'src'
  palette:
    primary: 'green'
    accent: 'light green'
  logo:
    icon: 'class'

# Copyright
copyright: 'Copyright &copy; 2019 - 2020 Certpages'

# Google Analytics
google_analytics:
  - 'UA-154979472-1'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition  
  - toc:
      permalink: true

# Plugins
plugins:
  - search

# Customization
extra:
  disqus: 'certpages'

# Page tree
nav:
  - Welcome: 'index.md'
  - Amazon Web Services:
    - 'Cloud Practitioner' : AWS/CloudPractitioner.md
    - 'Solutions Architect – Associate' : AWS/SolutionsArchitect–Associate.md
    - 'Developer - Associate' : AWS/Developer-Associate.md
    - 'SysOps Administrator - Associate' : AWS/SysOpsAdministrator-Associate.md
    - 'Solutions Architect - Professional' : AWS/SolutionsArchitect-Professional.md
    - 'DevOps Engineer - Professional' : AWS/DevOpsEngineer-Professional.md
    - 'Advanced Networking - Specialty' : AWS/AdvancedNetworking-Specialty.md
    - 'Big Data - Specialty' : AWS/BigData-Specialty.md
    - 'Security - Specialty' :  AWS/Security-Specialty.md
    - 'Machine Learning – Specialty' : AWS/MachineLearning–Specialty.md
    - 'Alexa Skill Builder - Specialty' : AWS/AlexaSkillBuilder-Specialty.md
  - CompTIA:
    - 'IT Fundamentals' : Comptia/ITFundamentals.md
    - 'A+' : Comptia/A+.md
    - 'Network+' : Comptia/Network+.md
    - 'Security+' : Comptia/Security+.md
    - 'Cloud+' : Comptia/Cloud+.md
    - 'Linux+' : Comptia/Linux+.md
    - 'Server+' : Comptia/Server+.md
    - 'CySA+' : Comptia/CySA+.md
    - 'CASP+' : Comptia/CASP+.md
    - 'PenTest+' : Comptia/PenTest+.md
    - 'Project+' : Comptia/Project+.md
    - 'Cloud Essentials+' : Comptia/CloudEssentials+.md
  - ISC2:
    - 'CISSP' : ISC2/CISSP.md
    - 'SSCP' : ISC2/SSCP.md
    - 'CCSP' : ISC2/CCSP.md
    - 'CAP' : ISC2/CAP.md
    - 'CSSLP' : ISC2/CSSLP.md
    - 'HCISPP' : ISC2/HCISPP.md